<a href="https://colab.research.google.com/github/uol-mediaprocessing/notebooks/blob/master/1-python-introduction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction to Python

In [0]:
print("hello world")

hello world


In Python, we can define variables like this:

In [0]:
a = 10 # integer
b = 5.0 # float
c = "hello world" # string
d = True # boolean
e = [a, b, c, d] # list

With the **type** operation, we can get the data type of a variable.

In [0]:
type(c)

str

To cast a variable, we use the desired data type as a function:

In [0]:
float(a)

10.0

There are several basic operations in Python:

In [0]:
# Addition
a + b

15.0

In [0]:
# Subtraction
a - b

5.0

In [0]:
# Multiplication
a * b

50.0

In [0]:
# Division
a / b

2.0

In [0]:
# Power
a ** b

100000.0

In [0]:
# Modulus
a % b

0.0

In Python, we define if operations like this. The indentation defines, where the block ends:

In [0]:
if a > 5:
    print("inside if")
print("outside if")

inside if
outside if


To check if an element is inside a list, we can use the **in** operator:

In [0]:
a in e

True

In [0]:
a not in e

False

Similarly, we can define a for loop like this:

In [0]:
for x in e:
    print(x)

10
5.0
hello world
True


We define a while loop like this:

In [0]:
i = 0
while True:
    print(i)
    i += 1
    if i > 3:
        break

0
1
2
3


Now, we can define a function like this:

In [0]:
def say_hello_to(name):
    print("hello", name)

say_hello_to("foo")

hello foo


# NumPy
Normal Python lists are not efficient for numerical programming. 

NumPy contains a powerful N-dimensional array object that uses C/C++ for more efficient computation.


In [0]:
import numpy as np

To convert a normal list to a NumPy array, we can use this function:

In [5]:
python_list = [1, 2, 3]
np_array = np.array(python_list)
np_array

array([1, 2, 3])

To generate an array, we can use several different initialization functions:

In [15]:
# intitialize with zeros
np.zeros((3, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [8]:
# initialize with ones
np.ones((2, 7))

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [16]:
# initialize with random values
np.random.rand(4, 4)

array([[0.58767327, 0.31160872, 0.91623106, 0.40050826],
       [0.37845213, 0.97609136, 0.41640783, 0.50662324],
       [0.73870304, 0.43114492, 0.66693378, 0.28086474],
       [0.39435176, 0.89701862, 0.43170388, 0.87600883]])

In NumPy, you can use several operators for easy array calculations.

In [0]:
a = np.array([4, 5, 6])
b = np.array([2, 4, 7])

In [24]:
# Addition
a + b

array([ 6,  9, 13])

In [25]:
# Element-wise multiplication
a * b

array([ 8, 20, 42])

In [26]:
# Multiplication with scalar
a * 2

array([ 8, 10, 12])

In [33]:
# Logical operations
print(a > b)
print(a < 5)
print(b == 4)

[ True  True False]
[ True False False]
[False  True False]


Also, there are many useful functions:

In [36]:
print(a.min())
print(a.max())
print(a.sum())

4
6
15


Indexing works in the same way as pythons lists:

In [37]:
a[1]

5

You can also get a slice of the array:

In [38]:
a[:2]

array([4, 5])